
import RightBar from "@/app/components/MainPage/RightBar";
import "./globals.css";


import type { Metadata } from 'next'
import LeftBar from "@/app/components/MainPage/LeftBar";

export const metadata: Metadata = {
  title: 'Repotor',
  description: 'Next.js I reporter application project',
}

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Repotor Dashboard",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
        
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
