"""Add cascade to user-likes relationship

Revision ID: 37926d3ea4a5
Revises: 819f18151bc3
Create Date: 2025-03-02 16:30:18.468777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37926d3ea4a5'
down_revision = '819f18151bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
