"""Add cascade to otrecord relationships

Revision ID: c68223dc46f9
Revises: 1e9dfe870b4c
Create Date: 2025-03-02 19:30:56.084842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68223dc46f9'
down_revision = '1e9dfe870b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookmarks_record_id_records', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookmarks_record_id_records'), 'records', ['record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_record_id_records', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_record_id_records'), 'records', ['record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_record_id_records', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_likes_record_id_records'), 'records', ['record_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_record_id_records'), type_='foreignkey')
        batch_op.create_foreign_key('fk_likes_record_id_records', 'records', ['record_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_record_id_records'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_record_id_records', 'records', ['record_id'], ['id'])

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookmarks_record_id_records'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bookmarks_record_id_records', 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###
